// Generated by wxt
import "wxt/browser";

declare module "wxt/browser" {
  export type PublicPath =
    | "/background.js"
    | "/chat-widget.html"
    | "/content-scripts/content.js"
    | "/placeholder-logo.png"
    | "/placeholder-logo.svg"
    | "/placeholder-user.jpg"
    | "/placeholder.jpg"
    | "/placeholder.svg"
    | "/sidepanel.html"
    | "/wallet-bridge.js"
  type HtmlPublicPath = Extract<PublicPath, `${string}.html`>
  export interface WxtRuntime {
    getURL(path: PublicPath): string;
    getURL(path: `${HtmlPublicPath}${string}`): string;
  }
}
